PizzaPlace/PizzaPlace/PizzaPlace/ViewModels/OrdersListViewModel.cs
using PizzaPlace.Models;

namespace PizzaPlace.ViewModels
{
    public class OrdersListViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Message { get; set; }
        public OrderStatus Status{ get; set; }
    }
}

PizzaPlace/PizzaPlace/PizzaPlace/Pages/Dashboard/Menu.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PizzaPlace.Pages.Dashboard
{
    [Authorize]
    public class MenuModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

PizzaPlace/PizzaPlace/PizzaPlace/Pages/Dashboard/OrdersList.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Mappings;
using PizzaPlace.Models;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;

namespace PizzaPlace.Pages.Admin
{
    [Authorize(Roles = "Admin, Cook, Delivery" )]
    public class OrdersListModel : PageModel
    {
        private readonly IOrderService _orderService;

        public OrdersListModel(IOrderService orderService)
        {
            _orderService = orderService;
        }

        public List<OrdersListViewModel> OrdersList { get; set; }

        public void OnGet()
        {
            var orders = _orderService.GetAll();
            OrdersList = orders.Select(x => x.ToOrderListViewModel()).ToList();
        }

        public void OnGetPending()
        {
            var orders = _orderService.GetByStatus(OrderStatus.Pending);
            OrdersList = orders.Select(x => x.ToOrderListViewModel()).ToList();
        }

        public void OnGetProcessed()
        {
            var orders = _orderService.GetByStatus(OrderStatus.Processed);
            OrdersList = orders.Select(x => x.ToOrderListViewModel()).ToList();
        }

        public void OnGetDone()
        {
            var orders = _orderService.GetByStatus(OrderStatus.Done);
            OrdersList = orders.Select(x => x.ToOrderListViewModel()).ToList();
        }

        public IActionResult OnGetSetProcessed(int id)
        {
            _orderService.SetStatus(id, OrderStatus.Processed);
            return RedirectToPage("OrdersList", "Pending");
        }

        public IActionResult OnGetSetDone(int id)
        {
            _orderService.SetStatus(id, OrderStatus.Done);
            return RedirectToPage("OrdersList", "Processed");
        }
    }
}

PizzaPlace/PizzaPlace/PizzaPlace/Pages/Dashboard/UsersList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Models;

namespace PizzaPlace.Pages.Dashboard
{
    public class UsersListModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersListModel(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public List<ApplicationUser> Users { get; set; }
        public List<IdentityRole> Roles { get; set; }

        public void OnGet()
        {
            Users = _userManager.Users.ToList();
            Roles = _roleManager.Roles.ToList();
        }

        public async Task<IActionResult> OnGetRemoveRole(string roleName, string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            await _userManager.RemoveFromRoleAsync(user, roleName);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnGetAddRole(string roleName, string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            await _userManager.AddToRoleAsync(user, roleName);

            return RedirectToPage();
        }

        public async Task<IActionResult> OnGetDeleteUser(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            await _userManager.DeleteAsync(user);

            return RedirectToPage();
        }
    }
}

PizzaPlace/PizzaPlace/PizzaPlace/Pages/Menu.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaPlace.Mappings;
using PizzaPlace.Models;
using PizzaPlace.Services.Interfaces;
using PizzaPlace.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace PizzaPlace.Pages
{
    public class MenuModel : PageModel
    {
        private readonly IMenuItemService _menuItemService;

        public MenuModel(IMenuItemService menuItemService)
        {
            _menuItemService = menuItemService;
        }

        public List<MenuItemViewModel> MenuItems { get; set; }

        public void OnGet()
        {
            List<MenuItem> menuItems = _menuItemService.GetAll();
            MenuItems = menuItems.Select(x => x.ToViewModel()).ToList();
        }
    }
}

PizzaPlace/PizzaPlace/PizzaPlace/Pages/Dashboard/Menu.cshtml
@page
@model PizzaPlace.Pages.Dashboard.MenuModel
@{
    ViewData["Title"] = "Dashboard menu";
}


<h2>Orders menu:</h2>
@if (User.IsInRole("Admin"))
{
    <a class="btn btn-primary" asp-page="/Dashboard/OrdersList">All orders</a>
    <a class="btn btn-primary" asp-page="/Dashboard/OrdersList" asp-page-handler="Pending">Pending orders</a>
    <a class="btn btn-primary" asp-page="/Dashboard/OrdersList" asp-page-handler="Processed">Processed orders</a>
    <a class="btn btn-primary" asp-page="/Dashboard/OrdersList" asp-page-handler="Done">Done orders</a>

    <h2>Users:</h2>
    <a class="btn btn-primary" asp-page="/Dashboard/UsersList">Users list</a>

    <h2>Offers:</h2>

    <h2>MenuItems:</h2>

}

@if (User.IsInRole("Cook"))
{
    <a class="btn btn-primary" asp-page="/Dashboard/OrdersList" asp-page-handler="Pending">Pending orders</a>
}


@if (User.IsInRole("Delivery"))
{
    <a class="btn btn-primary" asp-page="/Dashboard/OrdersList" asp-page-handler="Processed">Processed orders</a>
}

PizzaPlace/PizzaPlace/PizzaPlace/Pages/Dashboard/OrdersList.cshtml
@page
@model PizzaPlace.Pages.Admin.OrdersListModel
@{
    ViewData["Title"] = "Orders list";
}


<h1>Orders List:</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Surname
            </th>
            <th>
                Phone
            </th>
            <th>
                Address
            </th>
            <th>
                Message
            </th>
            <th>
                Status
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model.OrdersList)
        {
        <tr>
            <td>@order.Name</td>
            <td>@order.Surname</td>
            <td>@order.Phone</td>
            <td>@order.Address</td>
            <td>@order.Message</td>
            <td>@order.Status</td>

            @if (order.Status == Models.OrderStatus.Pending)
            {
                <td>
                    <a class="btn btn-success" asp-page="/Dashboard/OrdersList" asp-page-handler="SetProcessed" asp-route-id="@order.Id">Set Processed</a>
                </td>
            }
            else if (order.Status == Models.OrderStatus.Processed)
            {
                <td>
                    <a class="btn btn-success" asp-page="/Dashboard/OrdersList" asp-page-handler="SetDone" asp-route-id="@order.Id">Set Done</a>
                </td>
            }else
            {
                <td class="text-success">Done</td>
            }
        </tr>
        }
    </tbody>
</table>

PizzaPlace/PizzaPlace/PizzaPlace/Pages/Dashboard/UsersList.cshtml
@page
@model PizzaPlace.Pages.Dashboard.UsersListModel
@{
    ViewData["Title"] = "Users list";
}

@using Microsoft.AspNetCore.Identity
@using PizzaPlace.Models

@inject UserManager<ApplicationUser> UserManager

<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                Email
            </th>
            <th>
                Roles
            </th>
            <th>
                Roles Actions
            </th>
            <th>
                User Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.Users)
        {
            <tr>
                <td>
                    @user.Email
                </td>
                <td>
                    @foreach (var role in await UserManager.GetRolesAsync(user))
                    {
                        <p>@role</p>
                    }
                </td>
                <td>
                    @foreach (var role in Model.Roles)
                    {
                        @if (await UserManager.IsInRoleAsync(user, role.Name))
                        {
                            <p>
                                <a asp-page-handler="RemoveRole" asp-route-roleName="@role.Name" asp-route-userId="@user.Id" class="text-danger">Remove @role.Name role</a>
                            </p>
                        }
                        else
                        {
                            <p>
                                <a asp-page-handler="AddRole" asp-route-roleName="@role.Name" asp-route-userId="@user.Id" class="text-success">Add @role.Name role</a>
                            </p>
                        }
                    }
                </td>
                <td>
                    <p>
                        <a asp-page-handler="DeleteUser" asp-route-userId="@user.Id" class="text-success">Delete user</a>
                    </p>
                </td>
            </tr>
        }
    </tbody>
</table>